language: objective-c
osx_image: xcode10
xcode_project: FYMSL
xcode_scheme: FYMSL
env:
  global:
  - FRAMEWORK_NAME=FYMSL
before_install:
- brew update
# - brew outdated carthage || brew upgrade carthage
#- carthage bootstrap --no-use-binaries --platform iOS 
# before_script:
# - carthage bootstrap
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: MxO87Ww+sLgDNW2tJbJlGp+xwyHXaHBT/bZJ5ITYsXTel5FpeRkqJ6SzMuJnF5jRxx+mSqa29f7l05or76N1TvHIWYkdbq8k7EKXqtxq+TDufjAUPxp2cnbOz5lklfAQKupZN59AbQg1UeDAt1sB/O39gQqCaDCJZXIjUXpWnxyV76GuUYFGIYAiFP/C5p7LErs3oAC3CoFPGpy7RAM709bJ+T9RyGSE2SzgRuEYSl4nBmrpfoJ2SCPqQYCWKiERW04L1+fy58ikvJGDDW2c2MmnEWfLiNccxjPKl+5CmXJ1u2CXNPAGEim2X+f1TBbOCWLVivDqh9uA4HeAylrsabc+pHm31Soi8MYmnYiS/lU9cbIYl0pacIzeVoL4VO3BCCuobnsydWfMu36gnySwItmraEYzqk4jqs1nNW5YXfoFawlQKvHx8aW7CJE1n8UkAIQG2h0BjIV0NDt1QwTajDbvwaCpFK+rNR4oSJi27OuJRC5CpI7F+RDsrjVOP++SJ8Fpj339i8YMh+9aWw8PHpXCeRd2cATYmEpW9fXuQRi2Nvl7LaZIUqnixni7X6CXoT+CpFLeqhjCIif9qdrE1GHKurcNGcD4oJWGE8YPApWFobmM0onke9BTTKuWV+sV3hQH4nBf/ZWR3w+5fzDYMcTeLbLv3XWOS1TOL3mpZdc=
  file: FYMSL.framework.zip
  on:
    repo: ifgyong/FYMSL
script:
- xcodebuild test -project "$PROJECT_NAME" -scheme "$SCHEME" -destination "$DESTINATION"
  -sdk "$SDK" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
